feat: workflow updates

diff --git a/synced/Alfred.alfredpreferences/workflows/user.workflow.B4D2FD01-74DA-4F9D-8CDC-55A0DA1BC793/search b/synced/Alfred.alfredpreferences/workflows/user.workflow.B4D2FD01-74DA-4F9D-8CDC-55A0DA1BC793/search
--- a/synced/Alfred.alfredpreferences/workflows/user.workflow.B4D2FD01-74DA-4F9D-8CDC-55A0DA1BC793/search
+++ b/synced/Alfred.alfredpreferences/workflows/user.workflow.B4D2FD01-74DA-4F9D-8CDC-55A0DA1BC793/search
@@ -10,6 +10,10 @@ SUFFIX="$2"
 # description of url to open
 URL_DESC="${3:-Project}"
 
+log() {
+  echo "$@" >> log.txt
+}
+
 if [[ -z "$GROUP" ]]; then
   SCOPE="users"
   # user id cache file location
@@ -33,24 +37,36 @@ else
   find .cache -type f -mtime +7 -name '*.json' -exec rm {} \;
 
   query=$1
-  hash=$(echo $query | md5 -q)
+  hash=$(echo "$query" | md5 -q)
+
+  log "Query: $query, Hash: $hash"
+
+  log "Query: $query, Hash: $hash"
 
   # cache file location
   fl=".cache/projects-$hash.json"
 
+  log "Attempting cache file: $fl"
+
   if [[ ! -f $fl ]]; then
+    log "Cache file not found, fetching from API"
+
     # project endpoint url
     url="$API_BASE/$SCOPE/$ID/projects?private_token=$TOKEN&include_subgroups=true&per_page=20&search=$query"
     # get and cache to file
-    curl $url >$fl
+    curl "$url" >"$fl"
   fi
 
+  log "Processing results"
+
   # build url from args and jq result
-  url_build=$([[ -z "$SUFFIX" ]] && echo ".web_url" || echo '([.web_url, "/-/'$SUFFIX'"] | join(""))')
+  url_build=$([[ -z "$SUFFIX" ]] && echo ".web_url" || echo '([.web_url, "/-/'"$SUFFIX"'"] | join(""))')
 
   # jq query
   jquery='map({title: (["Open '$URL_DESC': ",.path] | join("")), subtitle: .path_with_namespace, arg:'$url_build'}) | {items:.}'
 
+  log "Sending Result: $jquery"
+
   # output items to alfred
-  jq "$jquery" $fl
+  jq "$jquery" "$fl"
 fi
